### ISSUE TITLE
Causes Side Effects with WIP limits

### ISSUE THREAD

**Issue by TurmRIC** [dmorlitz/kanboard-duedate#2]
## Actual Behaviour
Column WIP limits to become per swimlane instead of across the whole column.
![kanboard-with-duedate](https://user-images.githubusercontent.com/10522059/34052519-5d034138-e188-11e7-89f2-c0819a0e2820.png)

## Expected Behaviour
WIP limits are unaffected.
![kanboard-without-duedate](https://user-images.githubusercontent.com/10522059/34052531-665d89b4-e188-11e7-8b2a-a4b98cfd50da.png)

**Comment by dmorlitz** [comment]
I am sorry but I do not understand exactly what you are trying to say here.  I am not sure that this is an issue with the plugin.  The 2 screenshots that you included both show the cards in the same order.  Since the "Test task Pi" is not at the bottom of the swimlane it is in, this lets me know that you are using the "board order" sort method.  In "board order" this plugin does nothing.  I have simply taken a standard board template and added a block of code to sort a returned array if the sort method is "date order".

Does your instance of Kanboard act different regarding this column if you remove this plugin?  Also, what version of Kanboard are you running?

**Comment by TurmRIC** [comment]
Yes the cards are both in the same order, the issue is the Highlighting of the column being above the WIP limit of 4 items. In the first screenshot (with the plugin installed) the column isn't highlighted even though it has 5 items in it. In the second (with the plugin uninstalled) it is highlighted. This is version 1.1.1 of kanboard.

**Comment by dmorlitz** [comment]
Thank you for the explanation. I don't use the WIP feature so I never
tested that. I will look into and see if I can get this fixed.

**Comment by dmorlitz** [comment]
I have updated this git repository with code to support the WIP in v 1.1.1 - apparently the way that WIP was done in this version was a significant change.

Thank you for finding this side effect.  Please let me know if this update either fixes or does not fix your issue.
