### ISSUE TITLE
Click to Change Sorting Results in "Access Forbidden"

### ISSUE THREAD

**Issue by Poikilos** [dmorlitz/kanboard-duedate#5]
* kanboard version: git 2019-03-01
* kanboard-duedate version: git 2019-03-04
* Installation method:
```
cd /var/www/html/kanboard/plugins
sudo -u www-data git clone https://github.com/dmorlitz/kanboard-duedate.git
sudo -u www-data mv kanboard-duedate DueDate
```

### Expected Behavior:
Clicking "...(click to change)" changes sorting from board order to due date order.

### Actual Behavior:
The screen only shows the KB logo and "Access Forbidden".

I couldn't tell whether the issue was related to #3 so here is the URL that the "...(click to change)" button tries just in case: <https://poikilos.dyndns.org/kanboard/?controller=ConfigController&action=show&plugin=DueDate&redirect=%252Fkanboard%252F%253Fcontroller%253DBoardViewController%2526action%253Dshow%2526project_id%253D12>

**Comment by dmorlitz** [comment]
I tried to recreate your problem on my system and I was not able to get the "Access Forbidden" message to  appear.

Your URL scheme is the one which does not use Apache's URL rewriting - which should be fine.  I was able to use this plugin on my system with the URL rewriting disabled and enabled.

Just out of curiosity, if you go the Kanboard settings page, do you see a "Board Due Date settings" tab label on the left-hand side?  If you see that - what happens if you click there?

Right now, this setting is applied at a system-wide level, which is why the menu appears there.  I have been thinking about changing this to a project level setting but I just haven't had the time yet.  Making setting changes here should act the same as pressing the button with the exception of it not redirecting you back to the board you came from, since you didn't come from a board.

As for the file structure, do you see the following files in /var/www/html/kanboard/plugins/DueDate:
Controller/ConfigController.php
LICENSE
Plugin.php
README.md
Template/config
Template/config/duedate.php
Template/config/sidebar.php
Template/project_header
Template/project_header/views.php
Template/board
Template/board/table_tasks_1.0.45.php
Template/board/table_tasks.php
releases/DueDate.zip

I usually install this through the Kanboard auto-installer interface, so I don't have to worry about the renaming of directories and files.

Could you also check the permissions on those files to make sure that they are owned and readable by the web-server?

**Comment by Poikilos** [comment]
It works after using the installer interface:
```bash
cd /var/www/html/kanboard
sudo -u www-data mv plugins/DueDate /tmp/
if [ ! -f config.php ]; then sudo -u www-data cp config.default.php config.php; fi
nano config.php
# then change value of PLUGIN_INSTALLER from false to true. Ctrl X, y to save.
```
* (then logged into kanboard as user with admin privs, clicked user avatar on top right, Plugins, Plugin Directory, then installed DueDate from there)
* After clicking on "...(click to change)" this time the configuration appeared and then after entering +90 years for undated items, I saved my settings and the sorting was correct (this configuration screen had not appeared when installed it via git clone).
I can't quite tell why there would be a problem with the install via git clone (I'm not sure whether not having a config.php was a problem or not--but I set up config.php as shown in the commands above to install the plugin via the web interface).
![kanboard sort by due date - nonworking left and working right install](https://user-images.githubusercontent.com/7557867/53753136-8209ea00-3e7e-11e9-86e0-42e607b275de.png)

**Comment by dmorlitz** [comment]
First - I am glad that you were able to make it work.

I am not sure why installing it via the user interface would be different from the git command - but now I know how to go about trying to reproduce the problem.

I would not worry about the DueDate.zip file - that is just a compressed version of the git repository.  That file is there because the convention in the autoinstaller is to have a ZIP file you can point to for people to download the latest version.

I will set up a new Kanboard installation and try installing it manually to see if I can reproduce your problem.  Since you are up and running, I will probably just move this down on my priority list a bit.

**Comment by dmorlitz** [comment]
I know this is an old thread but I wanted to let you know that I have changed this Plugin to allow configuration at the project level instead of at the system level.  It turns out that users are not always able to access system-wide configuration (as you would expect) which might have been the original cause of your error.  Please update to the new version if you would like the ability to sort boards differently.

**Comment by Poikilos** [comment]
I can click on it with an unpriveleged user now. Thanks.
